import type { StatusDefinition } from "../types";
import { T, dmg, heal } from "./dsl";

/**
 * Statuts (buffs / debuffs).
 * Durée : décrémentée à la fin de chaque tour ; « 2 tours » = le tour courant et le suivant.
 * Les effets sur la durée (Brûlure, Venin, Régénération) se déclenchent en fin de tour,
 * AVANT le décompte, donc un statut de 2 tours agit 2 fois. [RULE D13]
 */
export const STATUSES: StatusDefinition[] = [
  {
    id: "brulure",
    name: "Brûlure",
    text: "En fin de tour, subit 1 dégât par cumul.",
    polarity: "DEBUFF",
    stacking: "STACK",
    maxStacks: 3,
    defaultDuration: 2,
    passives: [{ trigger: { on: "ON_TURN_END", effects: [dmg(T.HOLDER, { from: "STACKS" }, "BRAISE", ["dot"])] } }],
  },
  {
    id: "venin",
    name: "Venin",
    text: "En fin de tour, subit 1 dégât par cumul.",
    polarity: "DEBUFF",
    stacking: "STACK",
    maxStacks: 5,
    defaultDuration: 3,
    passives: [{ trigger: { on: "ON_TURN_END", effects: [dmg(T.HOLDER, { from: "STACKS" }, "OMBRE", ["dot"])] } }],
  },
  {
    id: "egide",
    name: "Égide",
    text: "Absorbe les dégâts reçus (1 point par cumul).",
    polarity: "BUFF",
    stacking: "STACK",
    maxStacks: 10,
    defaultDuration: 2,
    passives: [{ modifier: { hook: "DAMAGE_IN", kind: "ABSORB_STACKS" } }],
  },
  {
    id: "epines",
    name: "Épines",
    text: "Quand un adversaire lui inflige des dégâts, il subit 1 dégât en retour.",
    polarity: "BUFF",
    stacking: "REFRESH",
    maxStacks: 1,
    defaultDuration: 2,
    passives: [
      {
        trigger: {
          on: "ON_DAMAGE_RECEIVED",
          filter: { otherIsFoe: true, notTags: ["reflected", "dot"] },
          effects: [dmg(T.EVENT_SOURCE, 1, "SEVE", ["reflected"])],
        },
      },
    ],
  },
  {
    id: "rage",
    name: "Rage",
    text: "+1 aux dégâts infligés par cumul.",
    polarity: "BUFF",
    stacking: "STACK",
    maxStacks: 3,
    defaultDuration: 2,
    passives: [{ modifier: { hook: "DAMAGE_OUT", kind: "ADD", value: 1 } }],
  },
  {
    id: "faiblesse",
    name: "Faiblesse",
    text: "−1 aux dégâts infligés.",
    polarity: "DEBUFF",
    stacking: "REFRESH",
    maxStacks: 1,
    defaultDuration: 2,
    passives: [{ modifier: { hook: "DAMAGE_OUT", kind: "ADD", value: -1 } }],
  },
  {
    id: "vulnerable",
    name: "Vulnérable",
    text: "Subit 50 % de dégâts en plus (arrondi inférieur).",
    polarity: "DEBUFF",
    stacking: "REFRESH",
    maxStacks: 1,
    defaultDuration: 1,
    passives: [{ modifier: { hook: "DAMAGE_IN", kind: "MUL", value: 1.5 } }],
  },
  {
    id: "surcharge",
    name: "Surcharge",
    text: "Les prochains dégâts infligés sont doublés (consommé à l'usage).",
    polarity: "BUFF",
    stacking: "STACK",
    maxStacks: 2,
    defaultDuration: 2,
    passives: [{ modifier: { hook: "DAMAGE_OUT", kind: "MUL", value: 2, consume: true } }],
  },
  {
    id: "regeneration",
    name: "Régénération",
    text: "En fin de tour, récupère 1 PV par cumul.",
    polarity: "BUFF",
    stacking: "STACK",
    maxStacks: 3,
    defaultDuration: 3,
    passives: [{ trigger: { on: "ON_TURN_END", effects: [heal(T.HOLDER, { from: "STACKS" })] } }],
  },
  {
    id: "intangible",
    name: "Intangible",
    text: "Immunisé contre tous les dégâts.",
    polarity: "BUFF",
    stacking: "REFRESH",
    maxStacks: 1,
    defaultDuration: 1,
    passives: [{ modifier: { hook: "DAMAGE_IN", kind: "IMMUNE" } }],
  },
  {
    id: "clairvoyance",
    name: "Clairvoyance",
    text: "+1 dé aux jets de Puissance.",
    polarity: "BUFF",
    stacking: "REFRESH",
    maxStacks: 1,
    defaultDuration: 2,
    passives: [{ modifier: { hook: "DICE", kind: "ADD", value: 1 } }],
  },
  {
    id: "maudit",
    name: "Maudit",
    text: "Ne peut pas récupérer de PV.",
    polarity: "DEBUFF",
    stacking: "REFRESH",
    maxStacks: 1,
    defaultDuration: 2,
    passives: [{ modifier: { hook: "HEAL_IN", kind: "MUL", value: 0 } }],
  },
  {
    id: "carapace",
    name: "Carapace",
    text: "−1 aux dégâts subis par cumul.",
    polarity: "BUFF",
    stacking: "STACK",
    maxStacks: 3,
    defaultDuration: 2,
    passives: [{ modifier: { hook: "DAMAGE_IN", kind: "ADD", value: -1 } }],
  },
  // --- Extension « Échos du Grimoire » ------------------------------------
  {
    id: "marque",
    name: "Marque",
    text: "Subit 1 dégât de plus par cumul, à chaque coup.",
    polarity: "DEBUFF",
    stacking: "STACK",
    maxStacks: 3,
    defaultDuration: 2,
    passives: [{ modifier: { hook: "DAMAGE_IN", kind: "ADD", value: 1 } }],
  },
  {
    id: "gel",
    name: "Gel",
    text: "−1 dé de Puissance et −8 à l'initiative.",
    polarity: "DEBUFF",
    stacking: "REFRESH",
    maxStacks: 1,
    defaultDuration: 2,
    passives: [{ modifier: { hook: "DICE", kind: "ADD", value: -1 } }, { modifier: { hook: "INITIATIVE", kind: "ADD", value: -8 } }],
  },
  {
    id: "hate",
    name: "Hâte",
    text: "+8 à l'initiative.",
    polarity: "BUFF",
    stacking: "REFRESH",
    maxStacks: 1,
    defaultDuration: 2,
    passives: [{ modifier: { hook: "INITIATIVE", kind: "ADD", value: 8 } }],
  },
  {
    id: "inspiration",
    name: "Inspiration",
    text: "+1 rune en main par cumul.",
    polarity: "BUFF",
    stacking: "STACK",
    maxStacks: 2,
    defaultDuration: 2,
    passives: [{ modifier: { hook: "HAND_SIZE", kind: "ADD", value: 1 } }],
  },
  {
    id: "aura-ardente",
    name: "Aura ardente",
    text: "En fin de tour, chaque adversaire subit 1 dégât.",
    polarity: "BUFF",
    stacking: "REFRESH",
    maxStacks: 1,
    defaultDuration: 2,
    passives: [{ trigger: { on: "ON_TURN_END", effects: [dmg(T.ALL_FOES, 1, "BRAISE", ["dot"])] } }],
  },
  {
    id: "lien-vital",
    name: "Lien vital",
    text: "Chaque fois qu'il blesse un adversaire, récupère 1 PV (3 fois par tour au plus).",
    polarity: "BUFF",
    stacking: "REFRESH",
    maxStacks: 1,
    defaultDuration: 2,
    passives: [{ trigger: { on: "ON_DAMAGE_DEALT", filter: { otherIsFoe: true }, maxPerTurn: 3, effects: [heal(T.HOLDER, 1)] } }],
  },
  {
    id: "vigueur-spectrale",
    name: "Vigueur spectrale",
    text: "+4 PV maximum pour la manche.",
    polarity: "BUFF",
    stacking: "IGNORE",
    maxStacks: 1,
    defaultDuration: "PERMANENT",
    passives: [{ modifier: { hook: "MAX_HP", kind: "ADD", value: 4 } }],
  },
];
